apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "octobox.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "octobox.name" . }}
    helm.sh/chart: {{ include "octobox.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "@daily"
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "octobox.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "octobox.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ .Chart.Name | quote}}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - "/usr/local/bin/rake"
              args:
                - "tasks:sync_notifications"
              env:
                {{- include "octobox.env" . | nindent 16}}
              volumeMounts:
                - mountPath: "/etc/localtime"
                  name: etc-timezone
          volumes:
            - name: etc-timezone
              hostPath:
                path: /etc/localtime

